# Expose application on http://NodeIP:30033

apiVersion: v1
kind: Service
metadata:
  name: hotpot-service
spec:
  type: NodePort
  selector:
    app: hotpot-service
  ports:
    - protocol: TCP
      port: 3333 # Port internally within the cluster
      targetPort: 3333 # This should match the port on which your application is listening within the Pod
      nodePort: 30033 # Static port on each node, values between 30000~32767

